wget http://www.equi4.com/pub/tk/tars/kitgen.tgz
wget http://www.equi4.com/pub/tk/tars/vfs.tar.gz
wget http://www.equi4.com/pub/tk/tars/zlib.tar.gz
wget http://www.equi4.com/pub/tk/tars/vqtcl.tgz
wget http://www.equi4.com/pub/tk/tars/tcl.tar.gz
wget http://pascal.scheffers.net/software/tclDict-8.5.2.tar.gz
wget http://www.starfishsystems.ca/cgi-bin/download?name=starfish
wget http://www-unix.globus.org/ftppub/gt4/4.2.1/installers/src/gt4.2.1-all-source-installer.tar.gz
wget http://kent.dl.sourceforge.net/sourceforge/classytcl/ClassyTcl-1.0.0.src.tar.gz
wget http://www.sqlite.org/sqlite-3_5_7-tea.tar.gz
