package ifneeded srmlite::cfg          0.2 [list source [file join $dir cfg.tcl]]
package ifneeded srmlite::soap         0.1 [list source [file join $dir soap.tcl]]
package ifneeded srmlite::http::server 0.2 [list source [file join $dir http_server.tcl]]
package ifneeded srmlite::srm::server  0.2 [list source [file join $dir srm_server.tcl]]
package ifneeded srmlite::cleanup      0.1 [list source [file join $dir cleanup.tcl]]
package ifneeded srmlite::templates    0.2 [list source [file join $dir templates.tcl]]
package ifneeded srmlite::utilities    0.1 [list source [file join $dir utilities.tcl]]
package ifneeded srmlite::frontend     0.1 [list source [file join $dir frontend.tcl]]
package ifneeded srmlite::backend      0.2 [list source [file join $dir backend.tcl]]
package ifneeded g2lite                0.1 [list load [file join $dir g2lite.so] g2lite]
package ifneeded gssctx                0.2 [list load [file join $dir gssctx.so] gssctx]
package ifneeded XOTcl               1.6.8 [list load [file join $dir libxotcl1.6.8.so] XOTcl]
package ifneeded tdom                0.8.3 "load [list [file join $dir libtdom0.8.3.so] tdom]; source [list [file join $dir tdom.tcl]]"
